server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min: 5


spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MicroservicesExample/config-repo
          default-label: main #branch
          timeout: 5
          clone-on-start: true
          force-pull: true
