apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
  labels:
    app: config-service
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
        - name: config-service
          image: config-service:1.0
          imagePullPolicy: IfNotPresent
          #Makes Kubernetes wait 5 seconds before sending the SIGTERM signal to the Pod by that Kubernetes will update its components to not to send new requests to the pod.( sleep is to avoid race condition)
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5"]
          ports:
            - containerPort: 9001
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            